//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreCru.Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public int Type { get; set; }
        public int Class { get; set; }
        public int Rarity { get; set; }
        public int Cost { get; set; }
        public int Price { get; set; }
        public int MaxLevel { get; set; }
        public int MaxExp { get; set; }
        public int minHP { get; set; }
        public int maxHp { get; set; }
        public int minAtk { get; set; }
        public int maxAtk { get; set; }
        public int minRcv { get; set; }
        public int maxRcv { get; set; }
        public Nullable<int> Special { get; set; }
        public Nullable<int> Ability { get; set; }
        public bool Global { get; set; }
    }
}
